data:
    image: busybox
    volumes:
        - /docker/volumes/restya/es:/usr/share/elasticsearch/data
        - /docker/volumes/restya/db:/var/lib/postgresql/data
        - /docker/volumes/restya/nginx:/usr/share/nginx/html
    command: tail -f /dev/null

elasticsearch:
    image: elasticsearch
    volumes_from:
        - data

postgres:
    image: postgres:9.6-alpine
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
    volumes_from:
        - data

restyaboard:
    image: restyaboard:0.4.2
    environment:
        RESTYA_DB_ADMIN_USER: postgres
        RESTYA_DB_ADMIN_PASSWORD: postgres
        RESTYA_DB_HOST: postgres
        RESTYA_DB_PORT: 5432
        RESTYA_DB_NAME: restyaboard
        RESTYA_DB_USER: restyaboard
        RESTYA_DB_PASSWORD: restyaboard
        RESTYA_TIMEZONE: Europe/Paris
        RESTYA_SERVER_NAME: centos-docker
        RESTYA_MAIL_DOMAIN: whisperingvault.net
        # Optional
        #RESTYA_MAIL_RELAYHOST: xxx
    links:
        - elasticsearch:elasticsearch
        - postgres:postgres
    ports:
        - 1234:80
    volumes_from:
        - data
